### ISSUE TITLE
YAML bug in docs

### ISSUE THREAD

**Issue by BartoszMilewski** [wetneb/sheetshow#14]
The first YAML example for a sheet diagram has incorrectly indented _outputs_ line.

**Comment by wetneb** [comment]
Thanks for noticing and reporting!

**Comment by BartoszMilewski** [comment]
I meant the first _sheet_ diagram (as opposed to string). 
- 1
- 2
- 2
slices:
- offset: 1
  inputs: 1
  outputs: 2
  nodes:
  - offset: 0
    inputs:
    - 1
      outputs:
    - 1
    - 1
  - offset: 2
    inputs: 2
    outputs: 2
    nodes:
    - offset: 0
      inputs:
      - 2
      - 2
      outputs:
      - 1
      - 1

It has several indentation errors.

**Comment by wetneb** [comment]
Yes sorry I was too quick off the marks here - I understood what you meant and I think  aa70598 fixed it.

**Comment by BartoszMilewski** [comment]
Have you tested it?

**Comment by wetneb** [comment]
OK this is becoming really embarrassing. Thanks for pointing it out - again!

**Comment by BartoszMilewski** [comment]
Not to be a stickler for detail, but the image in the documentation has labels on it.

**Comment by BartoszMilewski** [comment]
I'd suggest testing all the examples. The user should be able to copy and paste them into the app.

**Comment by wetneb** [comment]
Yes it obviously makes sense. I am a bit short on time to work on this at the moment but if you feel like to submit a pull request that would be most welcome of course!
